name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.set-matrix.outputs.distros }}
      builds: ${{ steps.set-matrix.outputs.builds }}
      distro_matrix: ${{ steps.set-matrix.outputs.distro_matrix }}
      rpm_matrix: ${{ steps.set-matrix.outputs.rpm_matrix }}
      deb_matrix: ${{ steps.set-matrix.outputs.deb_matrix }}
      stagetwo_matrix: ${{ steps.set-matrix.outputs.stagetwo_matrix }}
      foreman_matrix: ${{ steps.set-matrix.outputs.foreman_matrix }}
      sunbeam_matrix: ${{ steps.set-matrix.outputs.sunbeam_matrix }}
    steps:
      - id: set-matrix
        run: |
          DISTRO_JSON='[
            {"name": "ubuntu-22.04",  "image": "",              "series": "jammy", "builds": ["deb", "snap"], "stages": "foreman"},
            {"name": "ubuntu-24.04",  "image": "",              "series": "noble", "builds": ["deb", "snap"], "stages": "two,sunbeam"},
            {"name": "ubuntu-latest", "image": "ubuntu:latest", "series": "",      "builds": ["deb"],         "stages": ""},
            {"name": "debian-12",     "image": "debian:12",                        "builds": ["deb"],         "stages": ""},
            {"name": "debian-13",     "image": "debian:13",                        "builds": ["deb"],         "stages": "two"},
            {"name": "fedora-43",     "image": "fedora:43",                        "builds": ["rpm"],         "stages": ""},
            {"name": "fedora-44",     "image": "fedora:44",                        "builds": ["rpm"],         "stages": ""},
            {"name": "centos-9",      "image": "quay.io/centos/centos:stream9",    "builds": ["rpm"],         "stages": ""},
            {"name": "centos-10",     "image": "quay.io/centos/centos:stream10",   "builds": ["rpm"],         "stages": "two"}
          ]'
          echo "distro_matrix=$(echo $DISTRO_JSON | jq -c .)" >> $GITHUB_OUTPUT

          RPM_JSON=$(echo "$DISTRO_JSON" | jq -c '[.[] | select(.name | contains("centos") or contains("fedora"))]')
          echo "rpm_matrix=$RPM_JSON" >> $GITHUB_OUTPUT

          DEB_JSON=$(echo "$DISTRO_JSON" | jq -c '[.[] | select(.name | contains("ubuntu") or contains("debian"))]')
          echo "deb_matrix=$DEB_JSON" >> $GITHUB_OUTPUT

          STAGETWO_JSON=$(echo "$DISTRO_JSON" | jq -c '[.[] | select(.stages | contains("two"))]')
          echo "stagetwo_matrix=$STAGETWO_JSON" >> $GITHUB_OUTPUT

          FOREMAN_JSON=$(echo "$DISTRO_JSON" | jq -c '[.[] | select(.stages | contains("foreman"))]')
          echo "foreman_matrix=$FOREMAN_JSON" >> $GITHUB_OUTPUT

          SUNBEAM_JSON=$(echo "$DISTRO_JSON" | jq -c '[.[] | select(.stages | contains("sunbeam"))]')
          echo "sunbeam_matrix=$SUNBEAM_JSON" >> $GITHUB_OUTPUT

  filters:
    runs-on: ubuntu-latest
    outputs:
      foreman: ${{ steps.filter_foreman.outputs.foreman }}
      sunbeam: ${{ steps.filter_sunbeam.outputs.sunbeam }}
      docs_count: ${{ steps.filter_docs.outputs.doc_files_count }}
      all_count: ${{ steps.filter_docs.outputs.all_files_count }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter_foreman
        with:
          filters: |
            foreman:
              - '.github/workflows/**'
              - 'sos/report/**/__init__.py'
              - '**/apache.py'
              - '**/foreman*.py'
              - '**/candlepin.py'
              - '**/pulp.py'
              - '**/pulpcore.py'
              - '**/valkey.py'
              - '**/foreman_setup.sh'

      - uses: dorny/paths-filter@v4
        id: filter_docs
        with:
          filters: |
            all_files:
              - '**'
            doc_files:
              - 'man/**'
              - 'docs/**'
              - 'po/**'
              - '**/*.md'
              - 'AUTHORS'
              - 'LICENSE'

      - uses: dorny/paths-filter@v4
        id: filter_sunbeam
        with:
          filters: |
            sunbeam:
              - '.github/workflows/**'
              - '**/__init__.py'
              - '**/sunbeam.py'
              - '**/sunbeam_hypervisor.py'
              - '**/juju.py'
              - '**/kubernetes.py'
              - '**/ovn_host.py'
              - '**/sunbeam_setup.sh'

  build_deb:
    needs: [filters, setup]
    if: needs.filters.outputs.all_count > needs.filters.outputs.docs_count
    strategy:
      matrix:
        distro: ${{ fromJson(needs.setup.outputs.deb_matrix) }}
    uses: ./.github/workflows/build-deb.yaml
    with:
      distro_image: ${{ matrix.distro.image }}
      distro_name: ${{ matrix.distro.name }}

  build_snap:
    needs: [filters, setup]
    if: needs.filters.outputs.all_count > needs.filters.outputs.docs_count
    uses: ./.github/workflows/build-snap.yaml

  sunbeam:
    needs: [filters, setup, build_deb, build_snap]
    if: needs.filters.outputs.sunbeam == 'true'
    strategy:
      matrix:
        distro: ${{ fromJson(needs.setup.outputs.sunbeam_matrix) }}
    uses: ./.github/workflows/avocado.yaml
    with:
      runs_on: '["self-hosted", "linux", "amd64", "${{ matrix.distro.series }}", "xlarge"]'
      distro_image: ${{ matrix.distro.image }}
      distro_name: ${{ matrix.distro.name }}
      builds: ${{ toJson(matrix.distro.builds) }}
      extra_script: ./tests/test_data/sunbeam_setup.sh
      needs_test_repo: true
      test_name: "sunbeam_tests"
      stage_name: "Sunbeam"
      sunbeam_ver: "2024.1/stable"
      can_fail: true
    secrets: inherit
